language: generic
sudo: false
dist: precise

env:
  global:
    BYOND_MAJOR="511"
    BYOND_MINOR="1385"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
  matrix:
    - TEST=CODE
    - TEST=MAP MAP_PATH=away_sites_testing
    - TEST=MAP MAP_PATH=example
    - TEST=MAP MAP_PATH=torch
    - TEST=MAP MAP_PATH=overmap_example
    - TEST=WEB

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - oracle-java8-set-default
      - python
      - python-pip

script:
  - test/run-test.sh

jobs:
  include:
    - stage: broadcast_sucess
      script:
        - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
      env: TEST=CODE

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
